name: Linux Pytest-Firefox Tests
on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main

env:
  MOZ_HEADLESS: 1
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Pytest-Firefox Linting
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Run Tests
        shell: bash
        run: make install_poetry lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    name: Pytest-Firefox Tests
    strategy:
      fail-fast: false
      matrix:
        firefox: ['latest-beta', 'latest-devedition', 'latest-nightly', 'latest-esr', 'latest']
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Firefox
        id: setup-firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: ${{ matrix.firefox }}
          
      - name: Display Firefox Version
        run: |
          echo Installed Firefox version: ${{ steps.setup-firefox.outputs.firefox-version }}
          
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run Tests
        shell: bash
        run: make install_poetry test
        
      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-firefox-report-${{ matrix.firefox }}
          path: results/report.html

  type-check:
    runs-on: ubuntu-latest
    name: Pytest-Firefox Type Checking
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Run Type Check
        shell: bash
        run: make install_poetry typecheck
